version: '3.8'

services:
  backend:
    restart: unless-stopped
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/usr/app

  frontend:
    restart: unless-stopped
    build:
      context: ./Frontend
    ports:
      - "80:80"
    volumes:
      - ./Frontend:/usr/app
